// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: albums.sql

package database

import (
	"context"
)

const cleanAlbums = `-- name: CleanAlbums :exec
DELETE FROM albums
`

func (q *Queries) CleanAlbums(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanAlbums)
	return err
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums(id, name, url_image)
VALUES($1, $2, $3)
RETURNING id, name, url_image
`

type CreateAlbumParams struct {
	ID       int32
	Name     string
	UrlImage string
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, createAlbum, arg.ID, arg.Name, arg.UrlImage)
	var i Album
	err := row.Scan(&i.ID, &i.Name, &i.UrlImage)
	return i, err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, name, url_image FROM albums WHERE id = $1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id int32) (Album, error) {
	row := q.db.QueryRowContext(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(&i.ID, &i.Name, &i.UrlImage)
	return i, err
}
