// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: song_genres.sql

package database

import (
	"context"
)

const createSongGenre = `-- name: CreateSongGenre :one
INSERT INTO song_genres(id, song_id, genre_id)
VALUES ($1, $2, $3)
RETURNING id, song_id, genre_id
`

type CreateSongGenreParams struct {
	ID      int32
	SongID  int32
	GenreID int32
}

func (q *Queries) CreateSongGenre(ctx context.Context, arg CreateSongGenreParams) (SongGenre, error) {
	row := q.db.QueryRowContext(ctx, createSongGenre, arg.ID, arg.SongID, arg.GenreID)
	var i SongGenre
	err := row.Scan(&i.ID, &i.SongID, &i.GenreID)
	return i, err
}
