import { FaGuitar, FaHeart, FaHeadphonesAlt, FaMusic, FaStar, FaRocket,FaDrum, FaRegGrinBeam, FaRegSmileBeam, 
  FaMicrophoneAlt, FaCrown, FaRecordVinyl, FaTree,FaSkullCrossbones, FaTheaterMasks, FaFeatherAlt, FaGlobe, 
  FaFlagUsa, FaMale, FaFemale, FaRegClock, FaCloud, FaWind, FaGhost, FaRadiationAlt, FaFire, FaBolt, FaMoon, 
  FaSnowflake, FaLeaf,FaPaintBrush, FaHome, FaFlag,FaFistRaised,FaGlobeAsia,FaVolumeUp} from "react-icons/fa";
import { GiMicrophone, GiViolin, GiTrumpet, GiSonicBoom, GiMusicalScore, GiJapaneseBridge, GiLaserBlast, 
  GiHeadshot } from "react-icons/gi";
import { MdAudiotrack, MdLibraryMusic } from "react-icons/md";
import { CgPiano } from "react-icons/cg";
import { PiDiscoBallDuotone } from "react-icons/pi";
import { FaCompactDisc, FaCouch, FaGamepad, FaKeyboard, FaRobot, FaSkull, FaYinYang } from "react-icons/fa6";
import { GenreListFormat } from "@/types/genreTypes";

export const genreList: GenreListFormat[] = [
  { name: 'Rock', icon: FaGuitar },
  {name: 'Alternative',icon: FaHeadphonesAlt},
  {name: 'Alternative Rock',icon: FaGuitar},
  { name: '90s', icon: FaRegSmileBeam },
  {name: 'Grunge',icon: FaSkullCrossbones},
  { name: 'Indie', icon: FaFeatherAlt},
  { name: 'Pop', icon: FaMusic },
  { name: 'British', icon: FaFlagUsa },
  { name: 'Love', icon: FaHeart, },
  { name: 'Britpop', icon: FaFlagUsa },
  { name: 'Indie Rock', icon: FaGuitar, },
  { name: '00s', icon: FaRegGrinBeam, },
  { name: 'Piano', icon: CgPiano },
  { name: 'Beautiful', icon: FaStar, },
  { name: 'Mellow', icon: FaCloud, },
  { name: 'Funk', icon: FaDrum, },
  { name: 'Electronic', icon: FaBolt, },
  {name: 'Dance',icon: PiDiscoBallDuotone,},
  {name: 'Metal',icon: FaSkullCrossbones,},
  { name: 'Hard Rock', icon: FaFire, },
  {name: 'Nu Metal',icon: FaRadiationAlt,},
  {name: 'Progressive Rock',icon: FaRocket,},
  {name: 'Classic Rock',icon: FaRecordVinyl,},
  { name: '80s', icon: FaRegSmileBeam, },
  { name: '70s', icon: FaRegClock, },
  { name: 'Experimental', icon: FaWind, },
  {name: 'Soundtrack',icon: FaTheaterMasks,},
  {name: 'Female Vocalists',icon: FaFemale,},
  {name: 'Heavy Metal',icon: FaSkullCrossbones,},
  { name: 'Chillout', icon: FaSnowflake, },
  { name: 'Rap', icon: GiMicrophone, },
  { name: '60s', icon: FaRegClock, },
  { name: 'Post Punk', icon: FaGhost, },
  { name: 'Pop Rock', icon: FaMusic, },
  { name: 'Punk', icon: FaFire, },
  { name: 'Punk Rock', icon: FaFire, },
  { name: 'Acoustic', icon: FaGuitar, },
  { name: 'Emo', icon: FaHeart, },
  { name: 'New Wave', icon: FaBolt, },
  { name: 'Chill', icon: FaSnowflake, },
  {name: 'Indie Pop',icon: FaFeatherAlt,},
  {name: 'Gothic Metal',icon: FaSkullCrossbones,},
  {name: 'Gothic',icon: FaSkullCrossbones,},
  {name: 'Thrash Metal',icon: FaRadiationAlt,},
  { name: 'Folk', icon: FaTree, },
  {name: 'Singer Songwriter',icon: GiMicrophone,},
  { name: 'Country', icon: FaFlagUsa, },
  { name: 'Cover', icon: FaRecordVinyl, },
  { name: 'Blues Rock', icon: FaGuitar, },
  { name: 'Psychedelic', icon: FaGhost, },
  {name: 'Psychedelic Rock',icon: FaGhost,},
  { name: 'Guitar', icon: FaGuitar, },
  { name: 'American', icon: FaFlagUsa, },
  { name: 'Ska', icon: GiTrumpet, },
  { name: 'Ambient', icon: FaWind, },
  { name: 'Blues', icon: FaGuitar, },
  { name: 'Oldies', icon: FaRecordVinyl, },
  { name: 'French', icon: FaPaintBrush, },
  {name: 'Male Vocalists',icon: FaMale,},
  { name: 'Reggae', icon: FaLeaf, },
  {name: 'Instrumental',icon: GiViolin,},
  { name: 'Jazz', icon: GiTrumpet, },
  { name: 'Avant Garde', icon: FaRocket, },
  { name: 'Industrial', icon: FaCrown, },
  { name: 'German', icon: FaGlobe, },
  {name: 'Synthpop',icon: MdAudiotrack,},
  {name: 'Hardcore',icon: FaSkullCrossbones,},
  {name: 'Metalcore',icon: FaSkullCrossbones,},
  {name: 'Screamo',icon: FaSkullCrossbones,},
  { name: 'Post Rock', icon: FaGuitar, },
  { name: 'Swedish', icon: FaGlobe, },
  {name: 'Doom Metal',icon: FaRadiationAlt,},
  { name: 'Power Metal', icon: FaFire, },
  { name: 'Rnb', icon: FaMusic, },
  { name: 'Soul', icon: FaHeart, },
  {name: 'Electro',icon: MdLibraryMusic,},
  { name: 'House', icon: FaHome, },
  { name: 'Techno', icon: FaBolt, },
  { name: 'Post Hardcore', icon: FaFire, },
  {name: 'Progressive Metal',icon: FaRocket,},
  { name: 'Russian', icon: FaFlag, },
  { name: 'Noise', icon: GiSonicBoom, },
  { name: 'Idm', icon: FaRobot, },
  {name: 'Symphonic Metal',icon: GiMusicalScore,},
  { name: 'Dark Ambient', icon: FaMoon, },
  { name: 'Drum And Bass', icon: FaDrum, },
  {name: 'Downtempo',icon: FaFeatherAlt,},
  { name: 'Lounge', icon: FaCouch, },
  { name: 'Trance', icon: FaStar, },
  { name: 'New Age', icon: FaYinYang, },
  { name: 'Black Metal', icon: FaSkull, },
  { name: 'Death Metal', icon: FaSkull, },
  {name: 'Classical',icon: GiMusicalScore,},
  {name: 'Japanese',icon: GiJapaneseBridge,},
  {name: 'Melodic Death Metal',icon: FaSkull,},
  {name: 'Grindcore',icon: FaFistRaised,},
  { name: 'Polish', icon: FaFlag,  },
  { name: "Videogame Music", icon: FaGamepad, },
  { name: "Composer", icon: GiMusicalScore, },
  { name: "Orchestral", icon: FaCompactDisc, },
  { name: "Symphonic", icon: GiMusicalScore, },
  { name: "Electronica", icon: FaRobot, },
  { name: "Nier", icon: FaGamepad, },
  { name: "Choral", icon: FaMicrophoneAlt, },
  { name: "Anime", icon: FaStar, },
  { name: "Asian", icon: FaGlobeAsia, },
  { name: "Japan", icon: GiJapaneseBridge, },
  { name: "Asian Music", icon: FaGlobeAsia, },
  { name: "Arranger", icon: FaKeyboard, },
  { name: "Asian Pop", icon: FaMusic, },
  { name: "Keigo Hoashi", icon: FaMusic, },
  { name: "Minecraft", icon: FaGamepad, },
  { name: "Trip-hop", icon: FaHeadphonesAlt, },
  { name: "Atmospheric", icon: FaCloud, },
  { name: "Ost", icon: FaRecordVinyl, },
  { name: "Korean", icon: FaGlobeAsia, },
  { name: "K-pop", icon: FaHeart, },
  { name: "Ballad", icon: FaTheaterMasks, },
  { name: "Lyn", icon: FaMicrophoneAlt, },
  { name: "Female", icon: FaFemale, },
  { name: "J-pop", icon: FaMusic, },
  { name: "Hip Hop", icon: FaMicrophoneAlt, },
  { name: "Jazz Rock", icon: GiTrumpet, },
  { name: "Opera", icon: FaTheaterMasks, },
  { name: "France", icon: FaFlag, },
  { name: "Epic", icon: GiLaserBlast, },
  { name: "Melancholic", icon: FaSnowflake, },
  { name: "Beatiful", icon: FaHeart, },
  { name: "Gangsta Rap", icon: GiHeadshot, },
  { name: "Hardcore Rap", icon: FaFistRaised, },
  { name: "Alternative Metal", icon: FaGuitar, },
  { name: "Rap-rock", icon: FaVolumeUp, }
];