// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package database

import (
	"context"
)

const cleanArtists = `-- name: CleanArtists :exec
DELETE FROM artists
`

func (q *Queries) CleanArtists(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanArtists)
	return err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateArtistParams struct {
	ID   int32
	Name string
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, arg.ID, arg.Name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name FROM artists WHERE id = $1
`

func (q *Queries) GetArtistByID(ctx context.Context, id int32) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
