// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package database

import (
	"context"
)

const addArtist = `-- name: AddArtist :one
INSERT INTO artists (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type AddArtistParams struct {
	ID   int32
	Name string
}

func (q *Queries) AddArtist(ctx context.Context, arg AddArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, addArtist, arg.ID, arg.Name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name FROM artists WHERE id = $1
`

func (q *Queries) GetArtist(ctx context.Context, id int32) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtist, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
