// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genres.sql

package database

import (
	"context"
)

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres(id, genre) 
VALUES($1, $2) 
RETURNING id, genre
`

type CreateGenreParams struct {
	ID    int32
	Genre string
}

func (q *Queries) CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error) {
	row := q.db.QueryRowContext(ctx, createGenre, arg.ID, arg.Genre)
	var i Genre
	err := row.Scan(&i.ID, &i.Genre)
	return i, err
}
