// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genres.sql

package database

import (
	"context"
)

const addGenre = `-- name: AddGenre :one
INSERT INTO genres(id, genre) 
VALUES($1, $2) 
RETURNING id, genre
`

type AddGenreParams struct {
	ID    int32
	Genre string
}

func (q *Queries) AddGenre(ctx context.Context, arg AddGenreParams) (Genre, error) {
	row := q.db.QueryRowContext(ctx, addGenre, arg.ID, arg.Genre)
	var i Genre
	err := row.Scan(&i.ID, &i.Genre)
	return i, err
}
