// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Album struct {
	ID       int32
	Name     string
	UrlImage string
}

type Artist struct {
	ID   int32
	Name string
}

type Genre struct {
	ID    int32
	Genre string
}

type Song struct {
	ID         int32
	Name       string
	SpotifyID  string
	UrlPreview string
	Duration   int32
	Year       int32
}

type SongArtist struct {
	ID       int32
	SongID   int32
	ArtistID int32
}

type SongDetail struct {
	ID               int32
	SongID           int32
	Danceability     float32
	Energy           float32
	TrackKey         float32
	Loudness         float32
	Mode             float32
	Speechiness      float32
	Acousticness     float64
	Instrumentalness float64
	Liveness         float32
	Valence          float32
	Tempo            float32
	TimeSignature    int32
}

type SongGenre struct {
	ID      int32
	SongID  int32
	GenreID int32
}
