// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: song_details.sql

package database

import (
	"context"
)

const cleanSongDetails = `-- name: CleanSongDetails :exec
DELETE FROM song_details
`

func (q *Queries) CleanSongDetails(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanSongDetails)
	return err
}

const createSongDetails = `-- name: CreateSongDetails :one
INSERT INTO song_details (id, song_id, danceability, energy, track_key, loudness, 
mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, time_signature)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, song_id, danceability, energy, track_key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, time_signature
`

type CreateSongDetailsParams struct {
	ID               int32
	SongID           int32
	Danceability     float32
	Energy           float32
	TrackKey         float32
	Loudness         float32
	Mode             float32
	Speechiness      float32
	Acousticness     float64
	Instrumentalness float64
	Liveness         float32
	Valence          float32
	Tempo            float32
	TimeSignature    int32
}

func (q *Queries) CreateSongDetails(ctx context.Context, arg CreateSongDetailsParams) (SongDetail, error) {
	row := q.db.QueryRowContext(ctx, createSongDetails,
		arg.ID,
		arg.SongID,
		arg.Danceability,
		arg.Energy,
		arg.TrackKey,
		arg.Loudness,
		arg.Mode,
		arg.Speechiness,
		arg.Acousticness,
		arg.Instrumentalness,
		arg.Liveness,
		arg.Valence,
		arg.Tempo,
		arg.TimeSignature,
	)
	var i SongDetail
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.Danceability,
		&i.Energy,
		&i.TrackKey,
		&i.Loudness,
		&i.Mode,
		&i.Speechiness,
		&i.Acousticness,
		&i.Instrumentalness,
		&i.Liveness,
		&i.Valence,
		&i.Tempo,
		&i.TimeSignature,
	)
	return i, err
}
