// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: song_artists.sql

package database

import (
	"context"
)

const createSongArtist = `-- name: CreateSongArtist :one
INSERT INTO song_artists(id, song_id, artist_id)
VALUES($1, $2, $3)
RETURNING id, song_id, artist_id
`

type CreateSongArtistParams struct {
	ID       int32
	SongID   int32
	ArtistID int32
}

func (q *Queries) CreateSongArtist(ctx context.Context, arg CreateSongArtistParams) (SongArtist, error) {
	row := q.db.QueryRowContext(ctx, createSongArtist, arg.ID, arg.SongID, arg.ArtistID)
	var i SongArtist
	err := row.Scan(&i.ID, &i.SongID, &i.ArtistID)
	return i, err
}
