// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: songs.sql

package database

import (
	"context"
)

const cleanSongs = `-- name: CleanSongs :exec
DELETE FROM songs
`

func (q *Queries) CleanSongs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanSongs)
	return err
}

const createSong = `-- name: CreateSong :one
INSERT INTO songs(id, name, spotify_id, url_preview, duration, year, album_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, spotify_id, url_preview, duration, year, album_id
`

type CreateSongParams struct {
	ID         int32
	Name       string
	SpotifyID  string
	UrlPreview string
	Duration   float32
	Year       int32
	AlbumID    int32
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, createSong,
		arg.ID,
		arg.Name,
		arg.SpotifyID,
		arg.UrlPreview,
		arg.Duration,
		arg.Year,
		arg.AlbumID,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpotifyID,
		&i.UrlPreview,
		&i.Duration,
		&i.Year,
		&i.AlbumID,
	)
	return i, err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, name, spotify_id, url_preview, duration, year, album_id FROM songs WHERE id = $1
`

func (q *Queries) GetSongByID(ctx context.Context, id int32) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpotifyID,
		&i.UrlPreview,
		&i.Duration,
		&i.Year,
		&i.AlbumID,
	)
	return i, err
}
