name: Continuous Integration Pipeline

on:    
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  Frontend-Pipeline:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run lint
        working-directory: ./frontend

      - name: Check Security
        run: npx eslint .
        working-directory: ./frontend

  Backend-Pipeline:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install dependencies
        run: npm install
        
      - name: Check style
        run: npm run lint
        working-directory: ./backend

      - name: Check security
        run: npx eslint .
        working-directory: ./backend

      - name: Run tests
        run: npm run test
        working-directory: ./backend

  Playwright-E2E-Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installing Frontend and Backend dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

      - name: Build Backend
        run: npm run build
        working-directory: ./backend

      - name: Install Playwright dependencies
        run: npm ci
        working-directory: ./e2e

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Run Server
        run: npm run start:prod &
        working-directory: ./backend
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_PORT: ${{ secrets.DB_PORT }}
          ELASTICSEARCH_NODE: ${{ secrets.ELASTICSEARCH_NODE }}

      - name: Running Playwright tests
        run: npm run test
        working-directory: ./e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30